ekf_se_odom:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true
  publish_tf: true

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odometry0: /odom
  odometry0_config: [true, true, false,
                     false, false, false,
                     false, false, false,
                     false, false, false,
                     false, false]

  imu0: /imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true,
                false, false]

  imu0_differential: false
  imu0_remove_gravitational_acceleration: true

