ekf_filter_node:
  frequency: 30
  sensor_timeout: 1.0
  two_d_mode: true
  publish_tf: true

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /odom
  odom0_config: [true,  true,  false,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]

  imu0: /imu/data
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, false,
                false, false, false]

  imu0_differential: false
  use_control: false

